name: Sync
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Checkout GitLab
        run: |
          git remote add gl https://github.com/badges/shields
          git pull gl master:gitlab-sync || true
          git checkout gitlab-sync
          git remote remove gl
      - name: Create Pull Request
        run: |
          git push --set-upstream origin gitlab-sync || true
          git push origin || true
          gh pr create -B master -H gitlab-sync --title 'Merge Upstream Changes' --body 'Automatic PR' || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
